image: gitpod/workspace-full:latest
tasks:
  - name: init
    init: |
      cd car-dealership-system-api
      bash ./run.sh
    command: |
      bash ./run.sh
  - name: build
    command: |
      echo "Project start!"
