tasks:
  - name: init
    init: |
      docker-compose pull
    command: |
      docker-compose up -d
      sleep 10
      gp sync-done start
  - name: backend_build
    command: docker-compose logs -f
    openMode: tab-after
