server:
  port: 8080
  servlet:
    context-path: /v1/car-dealership-system-api

spring:
  application:
    name: car-dealership-system-api
  datasource:
    username: ${DB_USERNAME:localdb}
    password: ${DB_PASSWORD:localdb}
    url: ${DB_URL:jdbc:postgresql://localhost:5555/car-dealership-system-db}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: liquibase/db-changelog-master.yml
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:technodrift.gg@gmail.com}
    password: ${MAIL_PASSWORD:default_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true